"""
Data Generator — Store B (ecom-store-b)
Generates realistic e-commerce data using Faker for Azure SQL Database.
Store B uses DIFFERENT column naming conventions from Store A.
This simulates real-world schema heterogeneity across regional systems.
Run: python generate_store_b.py
Output: ../adf/source_scripts/store_b_initial_load.sql
"""

import random
from datetime import datetime, timedelta
from faker import Faker

fake = Faker()
Faker.seed(99)
random.seed(99)

# ─── Configuration ───────────────────────────────────────────────
NUM_CUSTOMERS = 1500
NUM_PRODUCTS = 400
NUM_ORDERS = 6000
NUM_ORDER_ITEMS = 15000
OUTPUT_FILE = "../adf/source_scripts/store_b_initial_load.sql"

CATEGORIES = [
    ("C001", "Electronics", None),
    ("C002", "Clothing", None),
    ("C003", "Home & Kitchen", None),
    ("C004", "Books", None),
    ("C005", "Sports & Outdoors", None),
    ("C006", "Smartphones", "C001"),
    ("C007", "Laptops", "C001"),
    ("C008", "Men's Wear", "C002"),
    ("C009", "Women's Wear", "C002"),
    ("C010", "Cookware", "C003"),
    ("C011", "Fiction", "C004"),
    ("C012", "Non-Fiction", "C004"),
    ("C013", "Fitness Equipment", "C005"),
    ("C014", "Audio & Headphones", "C001"),
    ("C015", "Furniture", "C003"),
]

PAYMENT_MODES = ["CC", "DC", "UPI", "NEFT", "COD", "PayPal", "EMI"]
ORDER_STATUSES = ["DELIVERED", "IN_TRANSIT", "PROCESSING", "CANCELLED", "RETURNED", "PENDING"]
VENDORS = [
    "Sunrise Distributors", "Delta Wholesale", "Phoenix Trading",
    "Coastal Imports", "Summit Retail Partners", "Horizon Supply Co.",
    "Atlas Goods International", "Pinnacle Sourcing", "Nova Ventures",
    "Zenith Suppliers"
]


def escape_sql(s):
    if s is None:
        return "NULL"
    return str(s).replace("'", "''")


def random_date(start_year=2023, end_year=2025):
    start = datetime(start_year, 1, 1)
    end = datetime(end_year, 12, 31)
    delta = end - start
    return start + timedelta(days=random.randint(0, delta.days))


def generate():
    lines = []
    lines.append("-- ============================================")
    lines.append("-- Store B Initial Load — Generated by Faker")
    lines.append(f"-- Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("-- Database: ecom-store-b")
    lines.append("-- NOTE: Store B uses DIFFERENT column names from Store A")
    lines.append("-- ============================================\n")
    lines.append("USE [ecom-store-b];\nGO\n")

    # ─── Product Categories (different column names!) ─────────────
    lines.append("-- ── Product Categories ────────────────────────")
    lines.append("TRUNCATE TABLE dbo.product_categories;\nGO\n")
    for cat_id, cat_name, parent in CATEGORIES:
        parent_val = f"'{parent}'" if parent else "NULL"
        lines.append(
            f"INSERT INTO dbo.product_categories (CatID, CatName, ParentCat) "
            f"VALUES ('{cat_id}', '{escape_sql(cat_name)}', {parent_val});"
        )
    lines.append("GO\n")

    # ─── Customer Info (DIFFERENT column names from Store A!) ─────
    lines.append("-- ── Customer Info (different schema from Store A) ──")
    customers = []
    for i in range(1, NUM_CUSTOMERS + 1):
        cust_id = f"CB-{i:05d}"
        fname = escape_sql(fake.first_name())
        lname = escape_sql(fake.last_name())
        email = f"{fname.lower()}.{lname.lower()}@{fake.free_email_domain()}"
        phone = fake.phone_number()[:15]
        street = escape_sql(fake.street_address())
        town = escape_sql(fake.city())
        region = fake.state_abbr()
        postal = fake.zipcode()
        create_dt = random_date(2023, 2024)
        update_dt = create_dt + timedelta(days=random.randint(0, 200))
        customers.append(cust_id)

        lines.append(
            f"INSERT INTO dbo.customer_info (CustID, FName, LName, EmailAddr, PhoneNum, "
            f"Street, Town, Region, PostalCode, CreateDt, UpdateDt) VALUES ("
            f"'{cust_id}', '{fname}', '{lname}', '{escape_sql(email)}', '{escape_sql(phone)}', "
            f"'{street}', '{town}', '{region}', '{postal}', "
            f"'{create_dt.strftime('%Y-%m-%d')}', '{update_dt.strftime('%Y-%m-%d')}');"
        )
    lines.append("GO\n")

    # ─── Product Catalog (DIFFERENT column names from Store A!) ───
    lines.append("-- ── Product Catalog (different schema from Store A) ──")
    products = []
    parent_cats = [c for c in CATEGORIES if c[2] is None]
    subcats_map = {
        "Electronics": ["Smartphones", "Laptops", "Tablets", "Audio", "Cameras"],
        "Clothing": ["Men's Wear", "Women's Wear", "Kids", "Accessories"],
        "Home & Kitchen": ["Cookware", "Furniture", "Decor", "Appliances"],
        "Books": ["Fiction", "Non-Fiction", "Academic", "Comics"],
        "Sports & Outdoors": ["Fitness", "Camping", "Cycling", "Running"],
    }
    for i in range(1, NUM_PRODUCTS + 1):
        prod_id = f"PB-{i:05d}"
        prod_name = escape_sql(fake.catch_phrase())
        cat = random.choice(parent_cats)
        category = cat[1]
        subcats = subcats_map.get(category, ["General"])
        subcat = random.choice(subcats)
        price = round(random.uniform(4.99, 3499.99), 2)
        avail_qty = random.randint(0, 600)
        vendor = random.choice(VENDORS)
        create_dt = random_date(2023, 2024)
        update_dt = create_dt + timedelta(days=random.randint(0, 150))
        products.append(prod_id)

        lines.append(
            f"INSERT INTO dbo.product_catalog (ProdID, ProdName, Cat, SubCat, "
            f"ListPrice, AvailableQty, VendorName, CreateDt, UpdateDt) VALUES ("
            f"'{prod_id}', '{escape_sql(prod_name)}', '{escape_sql(category)}', "
            f"'{escape_sql(subcat)}', {price}, {avail_qty}, "
            f"'{escape_sql(vendor)}', '{create_dt.strftime('%Y-%m-%d')}', "
            f"'{update_dt.strftime('%Y-%m-%d')}');"
        )
    lines.append("GO\n")

    # ─── Order Log (DIFFERENT column names from Store A!) ─────────
    lines.append("-- ── Order Log (different schema from Store A) ──")
    orders = []
    for i in range(1, NUM_ORDERS + 1):
        ord_id = f"OB-{i:06d}"
        cust_id = random.choice(customers)
        ord_date = random_date(2024, 2025)
        ship_dt = ord_date + timedelta(days=random.randint(1, 14))
        status = random.choice(ORDER_STATUSES)
        grand_total = round(random.uniform(10.0, 6000.0), 2)
        pay_mode = random.choice(PAYMENT_MODES)
        ship_addr = escape_sql(fake.address().replace("\n", ", "))
        create_dt = ord_date
        update_dt = ord_date + timedelta(days=random.randint(0, 30))
        orders.append((ord_id, ord_date))

        lines.append(
            f"INSERT INTO dbo.order_log (OrdID, CustID, OrdDate, ShipDt, OrdStatus, "
            f"GrandTotal, PayMode, ShipAddr, CreateDt, UpdateDt) VALUES ("
            f"'{ord_id}', '{cust_id}', '{ord_date.strftime('%Y-%m-%d')}', "
            f"'{ship_dt.strftime('%Y-%m-%d')}', '{status}', {grand_total}, '{pay_mode}', "
            f"'{ship_addr}', '{create_dt.strftime('%Y-%m-%d')}', "
            f"'{update_dt.strftime('%Y-%m-%d')}');"
        )
    lines.append("GO\n")

    # ─── Order Details (DIFFERENT column names from Store A!) ─────
    lines.append("-- ── Order Details (different schema from Store A) ──")
    for i in range(1, NUM_ORDER_ITEMS + 1):
        detail_id = f"DB-{i:06d}"
        ord_id, ord_date = random.choice(orders)
        prod_id = random.choice(products)
        qty = random.randint(1, 8)
        price = round(random.uniform(4.99, 1199.99), 2)
        discount_pct = round(random.uniform(0, 30), 1)
        amount = round(qty * price * (1 - discount_pct / 100), 2)
        create_dt = ord_date

        lines.append(
            f"INSERT INTO dbo.order_details (DetailID, OrdID, ProdID, Qty, Price, "
            f"DiscountPct, Amount, CreateDt) VALUES ("
            f"'{detail_id}', '{ord_id}', '{prod_id}', {qty}, {price}, "
            f"{discount_pct}, {amount}, '{create_dt.strftime('%Y-%m-%d')}');"
        )
    lines.append("GO\n")

    lines.append("-- ═══════════════════════════════════════════════")
    lines.append(f"-- Total Records: {NUM_CUSTOMERS} customers, {NUM_PRODUCTS} products,")
    lines.append(f"--   {NUM_ORDERS} orders, {NUM_ORDER_ITEMS} order details, {len(CATEGORIES)} categories")
    lines.append("-- ═══════════════════════════════════════════════")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"✅ Store B initial load generated: {OUTPUT_FILE}")
    print(f"   Customers: {NUM_CUSTOMERS}, Products: {NUM_PRODUCTS}")
    print(f"   Orders: {NUM_ORDERS}, Order Details: {NUM_ORDER_ITEMS}")


if __name__ == "__main__":
    generate()
