"""
Data Generator — Store A (ecom-store-a)
Generates realistic e-commerce data using Faker for Azure SQL Database.
Store A uses standard naming conventions.
Run: python generate_store_a.py
Output: ../adf/source_scripts/store_a_initial_load.sql
"""

import random
from datetime import datetime, timedelta
from faker import Faker

fake = Faker()
Faker.seed(42)
random.seed(42)

# ─── Configuration ───────────────────────────────────────────────
NUM_CUSTOMERS = 2000
NUM_PRODUCTS = 500
NUM_ORDERS = 8000
NUM_ORDER_ITEMS = 20000
OUTPUT_FILE = "../adf/source_scripts/store_a_initial_load.sql"

CATEGORIES = [
    ("CAT-001", "Electronics", None),
    ("CAT-002", "Clothing", None),
    ("CAT-003", "Home & Kitchen", None),
    ("CAT-004", "Books", None),
    ("CAT-005", "Sports & Outdoors", None),
    ("CAT-006", "Smartphones", "CAT-001"),
    ("CAT-007", "Laptops", "CAT-001"),
    ("CAT-008", "Men's Wear", "CAT-002"),
    ("CAT-009", "Women's Wear", "CAT-002"),
    ("CAT-010", "Cookware", "CAT-003"),
    ("CAT-011", "Fiction", "CAT-004"),
    ("CAT-012", "Non-Fiction", "CAT-004"),
    ("CAT-013", "Fitness Equipment", "CAT-005"),
    ("CAT-014", "Audio & Headphones", "CAT-001"),
    ("CAT-015", "Furniture", "CAT-003"),
]

SUBCATEGORIES = {
    "Electronics": ["Smartphones", "Laptops", "Tablets", "Audio", "Cameras"],
    "Clothing": ["Men's Wear", "Women's Wear", "Kids", "Accessories"],
    "Home & Kitchen": ["Cookware", "Furniture", "Decor", "Appliances"],
    "Books": ["Fiction", "Non-Fiction", "Academic", "Comics"],
    "Sports & Outdoors": ["Fitness", "Camping", "Cycling", "Running"],
}

PAYMENT_METHODS = ["Credit Card", "Debit Card", "UPI", "Net Banking", "Cash on Delivery", "Wallet"]
ORDER_STATUSES = ["Delivered", "Shipped", "Processing", "Cancelled", "Returned", "Pending"]
SUPPLIERS = [
    "Global Supplies Inc.", "Prime Distributors", "Metro Wholesale",
    "Eastern Trading Co.", "Western Imports Ltd.", "National Retailers",
    "Pacific Goods Corp.", "Continental Sourcing", "Urban Supply Chain",
    "Apex Vendors LLC"
]


def escape_sql(s):
    """Escape single quotes for SQL insertion."""
    if s is None:
        return "NULL"
    return str(s).replace("'", "''")


def random_date(start_year=2023, end_year=2025):
    """Generate a random date between start_year and end_year."""
    start = datetime(start_year, 1, 1)
    end = datetime(end_year, 12, 31)
    delta = end - start
    return start + timedelta(days=random.randint(0, delta.days))


def generate():
    lines = []
    lines.append("-- ============================================")
    lines.append("-- Store A Initial Load — Generated by Faker")
    lines.append(f"-- Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("-- Database: ecom-store-a")
    lines.append("-- ============================================\n")
    lines.append("USE [ecom-store-a];\nGO\n")

    # ─── Product Categories ──────────────────────────────────────
    lines.append("-- ── Product Categories ────────────────────────")
    lines.append("TRUNCATE TABLE dbo.product_categories;\nGO\n")
    for cat_id, cat_name, parent in CATEGORIES:
        parent_val = f"'{parent}'" if parent else "NULL"
        lines.append(
            f"INSERT INTO dbo.product_categories (CategoryID, CategoryName, ParentCategory) "
            f"VALUES ('{cat_id}', '{escape_sql(cat_name)}', {parent_val});"
        )
    lines.append("GO\n")

    # ─── Customers ───────────────────────────────────────────────
    lines.append("-- ── Customers ────────────────────────────────")
    customers = []
    for i in range(1, NUM_CUSTOMERS + 1):
        cust_id = f"CUST-A-{i:05d}"
        fname = escape_sql(fake.first_name())
        lname = escape_sql(fake.last_name())
        email = f"{fname.lower()}.{lname.lower()}@{fake.free_email_domain()}"
        phone = fake.phone_number()[:15]
        address = escape_sql(fake.street_address())
        city = escape_sql(fake.city())
        state = fake.state_abbr()
        zipcode = fake.zipcode()
        created = random_date(2023, 2024)
        modified = created + timedelta(days=random.randint(0, 180))
        customers.append(cust_id)

        lines.append(
            f"INSERT INTO dbo.customers (CustomerID, FirstName, LastName, Email, Phone, "
            f"Address, City, State, ZipCode, CreatedDate, ModifiedDate) VALUES ("
            f"'{cust_id}', '{fname}', '{lname}', '{escape_sql(email)}', '{escape_sql(phone)}', "
            f"'{address}', '{city}', '{state}', '{zipcode}', "
            f"'{created.strftime('%Y-%m-%d')}', '{modified.strftime('%Y-%m-%d')}');"
        )
    lines.append("GO\n")

    # ─── Products ────────────────────────────────────────────────
    lines.append("-- ── Products ─────────────────────────────────")
    products = []
    parent_cats = [c for c in CATEGORIES if c[2] is None]
    for i in range(1, NUM_PRODUCTS + 1):
        prod_id = f"PROD-A-{i:05d}"
        prod_name = escape_sql(fake.catch_phrase())
        cat = random.choice(parent_cats)
        category = cat[1]
        subcats = SUBCATEGORIES.get(category, ["General"])
        subcategory = random.choice(subcats)
        price = round(random.uniform(5.99, 2999.99), 2)
        stock = random.randint(0, 500)
        supplier = random.choice(SUPPLIERS)
        created = random_date(2023, 2024)
        modified = created + timedelta(days=random.randint(0, 120))
        products.append(prod_id)

        lines.append(
            f"INSERT INTO dbo.products (ProductID, ProductName, Category, SubCategory, "
            f"Price, StockQty, Supplier, CreatedDate, ModifiedDate) VALUES ("
            f"'{prod_id}', '{escape_sql(prod_name)}', '{escape_sql(category)}', "
            f"'{escape_sql(subcategory)}', {price}, {stock}, "
            f"'{escape_sql(supplier)}', '{created.strftime('%Y-%m-%d')}', "
            f"'{modified.strftime('%Y-%m-%d')}');"
        )
    lines.append("GO\n")

    # ─── Orders ──────────────────────────────────────────────────
    lines.append("-- ── Orders ──────────────────────────────────")
    orders = []
    for i in range(1, NUM_ORDERS + 1):
        order_id = f"ORD-A-{i:06d}"
        cust_id = random.choice(customers)
        order_date = random_date(2024, 2025)
        ship_date = order_date + timedelta(days=random.randint(1, 14))
        status = random.choice(ORDER_STATUSES)
        total = round(random.uniform(15.0, 5000.0), 2)
        payment = random.choice(PAYMENT_METHODS)
        ship_addr = escape_sql(fake.address().replace("\n", ", "))
        insert_date = order_date
        modified = order_date + timedelta(days=random.randint(0, 30))
        orders.append((order_id, order_date))

        lines.append(
            f"INSERT INTO dbo.orders (OrderID, CustomerID, OrderDate, ShipDate, Status, "
            f"TotalAmount, PaymentMethod, ShippingAddress, InsertDate, ModifiedDate) VALUES ("
            f"'{order_id}', '{cust_id}', '{order_date.strftime('%Y-%m-%d')}', "
            f"'{ship_date.strftime('%Y-%m-%d')}', '{status}', {total}, '{payment}', "
            f"'{ship_addr}', '{insert_date.strftime('%Y-%m-%d')}', "
            f"'{modified.strftime('%Y-%m-%d')}');"
        )
    lines.append("GO\n")

    # ─── Order Items ─────────────────────────────────────────────
    lines.append("-- ── Order Items ──────────────────────────────")
    for i in range(1, NUM_ORDER_ITEMS + 1):
        item_id = f"ITEM-A-{i:06d}"
        order_id, order_date = random.choice(orders)
        prod_id = random.choice(products)
        qty = random.randint(1, 10)
        unit_price = round(random.uniform(5.99, 999.99), 2)
        discount = round(random.uniform(0, 0.3), 2)
        line_total = round(qty * unit_price * (1 - discount), 2)
        insert_date = order_date

        lines.append(
            f"INSERT INTO dbo.order_items (OrderItemID, OrderID, ProductID, Quantity, "
            f"UnitPrice, Discount, LineTotal, InsertDate) VALUES ("
            f"'{item_id}', '{order_id}', '{prod_id}', {qty}, {unit_price}, "
            f"{discount}, {line_total}, '{insert_date.strftime('%Y-%m-%d')}');"
        )
    lines.append("GO\n")

    lines.append("-- ═══════════════════════════════════════════════")
    lines.append(f"-- Total Records: {NUM_CUSTOMERS} customers, {NUM_PRODUCTS} products,")
    lines.append(f"--   {NUM_ORDERS} orders, {NUM_ORDER_ITEMS} order items, {len(CATEGORIES)} categories")
    lines.append("-- ═══════════════════════════════════════════════")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"✅ Store A initial load generated: {OUTPUT_FILE}")
    print(f"   Customers: {NUM_CUSTOMERS}, Products: {NUM_PRODUCTS}")
    print(f"   Orders: {NUM_ORDERS}, Order Items: {NUM_ORDER_ITEMS}")


if __name__ == "__main__":
    generate()
